spring:
  # 서버 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  # 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 20
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
  # JWT 설정
  jwt:
    secret: ${JWT_SECRET}
# 카카오워크 API 설정
kakaowork:
  api:
    base-url: ${KAKAOWORK_API_URL}
    app-key: ${KAKAOWORK_API_KEY}
# object storage 추가 필요
kakaocloud:
  object-storage:
    iam:
      access-key: ${STORAGE_ACCESS_KEY}
      secret-key: ${STORAGE_SECRET_KEY}
      user-id: ${STORAGE_USER_ID}
      project-id: ${STORAGE_PROJECT_ID}
    endpoint: ${STORAGE_ENDPOINT}
    region: ${STORAGE_REGION}
    bucket-name: ${STORAGE_NAME}
# 로깅 설정
logging:
  level:
    root: info